---
- name: Create .my.cnf file for MySQL root user
  copy:
    dest: /root/.my.cnf
    content: |
      [client]
      user=root
      password={{ mysql_root_password }}
    owner: root
    group: root
    mode: '0600'

- name: Backup MySQL database
  shell: mysqldump --defaults-file=/root/.my.cnf --all-databases > /root/db_backup.sql

